# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7928837608c41da8c672a26c0250ed92"
name = "myoncarehub"
handle = "myoncarehub-1"
application_url = "https://myoncarehub.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[auth]
redirect_urls = [
  "https://myoncarehub.gadget.app/api/connections/auth/shopify/callback"
]
