name = "myoncare Connector"
type = "flow_action"
handle = "fulfillment-flow-action"
runtime_url = "https://myoncarehub.gadget.app/flow-ext/fulfill"
schema = "./schema.graphql"
api_version = "2023-07"
return_type_ref = "Result"
description = "Generate and store a shortened URL for individual order line items"

[flow_action]
title = "Line Item URL Shortener"

[settings]
  [[settings.fields]]
  key = "orderId"
  type = "single_line_text_field"
  name = "The Order ID"
  required = true
  description = "The Order ID"

  [[settings.fields]]
  key = "lineItemsIDs"
  type = "single_line_text_field"
  name = "Line Item IDs"
  required = true
  description = "The line Item IDs"

  [[settings.fields]]
  key = "lineItemsPics"
  type = "single_line_text_field"
  name = "Line Item Photos"
  required = true
  description = "The line Item Photos"
  
  [[settings.fields]]
  key = "lineItemQuantities" 
  type = "single_line_text_field"
  name = "Line Item Quantities"
  required = true
  description = "The Quantities Required from all line Items"

  [[settings.fields]]
  key = "lineItemLongUrls"
  type = "single_line_text_field"
  name = "LongURL"
  required = true
  description = "The Pathway Long URLs for all line items"