name = "Send Activation Email"
type = "flow_action"
handle = "send-activation-email"
runtime_url = "https://myoncarehub.gadget.app/flow-ext/order-email"
schema = "./schema.graphql"
api_version = "2023-07"
return_type_ref = "Result"
description = "Send an email to the customer for each paid individual order contains the shorturls for the lineItems Purchased"

[flow_action]
title = "Send Activation Email Block"
[settings]
  [[settings.fields]]
  key = "orderId"
  type = "single_line_text_field"
  name = "The Order ID"
  required = true
  description = "The Order ID"