name = "Send Activation Email"
type = "flow_action"
handle = "send-activation-email"
runtime_url = "shopify"
schema = "./schema.graphql"
api_version = "2023-07"
return_type_ref = "Result"
description = "Send an email to the customer for each paid individual order contains the shorturls for the lineItems Purchased"

[flow_action]
title = "Send Activation Email Block"
[settings]
  [[settings.fields]]
  key = "order"
  type = "object"
  name = "Order"
  required = true
  description = "Order information"
  
    [[settings.fields.fields]]
    key = "id"
    type = "single_line_text_field"
    name = "Order ID"
    required = true
    description = "The Order ID"